name: PR Preview Deployment

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js (if needed)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install  # or skip if plain HTML/CSS

      - name: Build site
        run: npm run build  # or your build command

      - name: Deploy to Preview Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # or your build output directory
          publish_branch: gh-pages-preview
          destination_dir: pr-${{ github.event.pull_request.number }}

      - name: Comment Preview URL
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 Preview deployed: https://${context.repo.owner}.github.io/${context.repo.repo}/pr-${context.issue.number}`
            })
