# .github/workflows/pr-preview.yml
name: PR Preview Deploy

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4

      # OPTIONAL: copy source files to a 'dist' folder if needed
      - name: Prepare site files
        run: |
          mkdir dist
          rsync -av --exclude=dist ./ dist/

      - name: Deploy to GitHub Pages (preview)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages-preview
          destination_dir: pr-${{ github.event.pull_request.number }}

      - name: Comment PR with Preview URL
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 Preview deployed: https://${context.repo.owner}.github.io/${context.repo.repo}/pr-${context.issue.number}`
            })
